utils::globalVariables(
  c(
    '.data',
    '.', '..pid_cols', '.N','.SD', 'ABSTRACTION_LEVEL', 'COHORT_DEFINITION_ID',
    'COHORT_DURATION', 'COHORT_END_DATE', 'COHORT_START_DATE', 'CONCEPT_ID',
    'CONCEPT_NAME', 'CONTROL_SUBJECT_COUNT', 'CONTROL_SUBJECT_PREVALENCE',
    'GENDER_CONCEPT_ID', 'HERITAGE', 'KSTEST', 'KSTEST_P_VALUE', 'LOGITTEST',
    'LOGITTEST_P_VALUE', 'NCONCEPTS', 'NPATIENTS', 'PERSON_ID', 'PRESENT', 'PREVALENCE',
    'PREVALENCE_DIFFERENCE_RATIO', 'SCALED_PREVALENCE', 'SUBJECT_ID',
    'TARGET_SUBJECT_COUNT', 'TARGET_SUBJECT_PREVALENCE', 'TIME_TO_EVENT',
    'YEAR_OF_BIRTH', 'ZTEST', 'ZTEST_P_VALUE', 'cohort_start_date', 'count', 'ordinal'
  )
)
