#' Generate a Heatmap Plot
#'
#' This function generates a heatmap using the CohortContrast GUI object.
#' It extracts necessary components from the ccObject and passes them to the
#' `createHeatmapPlot` function to generate the plot.
#'
#' @param ccObject An object returned by the CohortContrast GUI, typically created
#'        when the "Create Visual Snapshot" button is pressed. It should contain
#'        target_row_annotation, target_col_annotation, and target_matrix components.
#' @return A plot object generated by `createHeatmapPlot`.
#' @examples
#' \dontrun{
#' # Assuming `ccObject` (visual snapshot) is already created via CohortContrast GUI
#' ccObject <- readRDS("./visual_snapshots/CohortContrastDataVisualSnapshot.rds")
#' getHeatmapPlot(ccObject)
#' }
#' @export
getHeatmapPlot <- function(ccObject) {
  createHeatmapPlot(
    ccObject$filtered_target
  )
}

#' @keywords internal
createHeatmapPlot <- function(filtered_target, isCorrelationView = FALSE) {
  plot_data = getHeatmapPlotData(filtered_target, isCorrelationView = isCorrelationView)

  # Check if any concepts left
  if (is.null(plot_data)) {
    return(getErrorPlot("After filtering there are < 2 concepts left"))
  }

  if (isCorrelationView) {
    return(getHeatmapPlotCorrelation(plot_data))
  } else {
    return(getHeatmapPlotRegular(plot_data))
  }
}

#' @keywords internal
getHeatmapPlotData <- function(filtered_target, isCorrelationView = FALSE) {
  if (is.null(filtered_target) ||
      nrow(filtered_target$target_row_annotation) == 0) {
    return(NULL)
  }

  if (is.null(nrow(filtered_target$target_matrix))) {
    filtered_target$target_matrix <-
      t(as.matrix(filtered_target$target_matrix)[1:length(filtered_target$target_matrix), , drop = FALSE])
    rownames(filtered_target$target_matrix) <-
      rownames(filtered_target$target_row_annotation)
  }

  heatmapData = list()

  if (isCorrelationView) {

    #Returns
    heatmapData$ordered_matrix = filtered_target$correlation_analysis$ordered_matrix
    heatmapData$hc_rows = filtered_target$correlation_analysis$hc_rows
    heatmapData$num_clusters = length(filtered_target$correlation_analysis$gaps_row) + 1
    heatmapData$ordered_groups = filtered_target$correlation_analysis$groups

  } else {

    filtered_target$target_row_annotation <-
      as.data.frame(filtered_target$target_row_annotation)
    filtered_target$target_col_annotation <-
      as.data.frame(filtered_target$target_col_annotation)
    rownames(filtered_target$target_col_annotation) <-
      filtered_target$target_col_annotation$PERSON_ID

    # Patient clustering
    col_clustering <-
      stats::hclust(stats::dist(t(filtered_target$target_matrix)))
    # Row reordering
    reordering <- filtered_target$target_row_annotation %>%
      tibble::rownames_to_column("CONCEPT_ID") %>%
      dplyr::group_by(.data$HERITAGE) %>%
      dplyr::arrange(dplyr::desc(.data$CONCEPT_NAME)) %>%
      dplyr::summarize(CONCEPT_ID = list(.data$CONCEPT_ID)) %>%
      dplyr::mutate(MATRIX = purrr::map(.data$CONCEPT_ID, ~ filtered_target$target_matrix[.x, , drop = F])) %>%
      dplyr::mutate(MATRIX = purrr::map(.data$MATRIX,
                                        function(x) {
                                          if (nrow(x) > 1) {
                                            x <- x[stats::hclust(stats::dist(x))$order, ]
                                          }

                                          return(x)
                                        }))
    tm <- as.data.frame(do.call(rbind, reordering$MATRIX))
    tm_gaps <- purrr::map_int(reordering$MATRIX, nrow) %>% cumsum()
    ordered_matrix <- as.matrix(tm)
    rownames(ordered_matrix) <-
      filtered_target$target_row_annotation[rownames(tm), ]$CONCEPT_NAME
    annotation_row <- filtered_target$target_row_annotation %>%
      dplyr::arrange(.data$CONCEPT_NAME) %>%
      tibble::remove_rownames() %>%
      tibble::column_to_rownames("CONCEPT_NAME") %>%
      dplyr::select(-.data$PREVALENCE_DIFFERENCE_RATIO)
    annotation_col <- filtered_target$target_col_annotation
    # Heritage colors pre-defined
    heritage_colors <- getHeritageColors(asList = TRUE)

    active_gender_colors <-
      c(
        Male = "purple",
        Female = "pink",
        Other = "lightblue"
      )

    # Filter heritage colors based on what's present in annotation_row
    active_heritage_colors <-
      heritage_colors[names(heritage_colors) %in% unique(annotation_row$HERITAGE)]
    active_gender_colors <-
      active_gender_colors[names(active_gender_colors) %in% unique(annotation_col$GENDER)]


    # Specify colors including a dynamic gradient for AGE
    annotation_colors <- list(
      AGE = colorRampPalette(c("lightblue", "firebrick"))(length(unique(
        annotation_col$AGE
      ))),
      GENDER = active_gender_colors,
      HERITAGE = active_heritage_colors,
      PREVALENCE = colorRampPalette(c("white", "purple"))(length(unique(
        annotation_row$PREVALENCE
      )))
    )

    # annotation_row
    annotation_row <- annotation_row %>%
      tibble::rownames_to_column("CONCEPT_NAME") %>%
      dplyr::arrange(.data$HERITAGE, dplyr::desc(toupper(.data$CONCEPT_NAME))) %>%
      tibble::column_to_rownames("CONCEPT_NAME")
    # Apply the same order to the matrix
    ordered_matrix <- ordered_matrix[rownames(annotation_row), ]

    if(is.null(rownames(ordered_matrix))){
      return(NULL)
    }
    rownames(ordered_matrix) <- unique_names(rownames(ordered_matrix))

    #Returns
    heatmapData$ordered_matrix = ordered_matrix
    heatmapData$annotation_row = annotation_row
    heatmapData$annotation_col = annotation_col
    heatmapData$annotation_colors = annotation_colors
    heatmapData$col_clustering = col_clustering
    heatmapData$tm_gaps = tm_gaps
  }

  return(heatmapData)
}

#' @keywords internal
getHeatmapPlotRegular <- function(plot_data) {

  heatmap <- pheatmap::pheatmap(
    plot_data$ordered_matrix,
    show_colnames = FALSE,
    annotation_row = plot_data$annotation_row %>% dplyr::select(.data$HERITAGE),
    annotation_col = plot_data$annotation_col %>% dplyr::select(.data$AGE, .data$GENDER),
    annotation_colors = plot_data$annotation_colors,
    cluster_cols = plot_data$col_clustering,
    cluster_rows = FALSE,
    gaps_row = plot_data$tm_gaps,
    color = c("#e5f5f9", "#2ca25f"),
    legend_breaks = c(0.25, 0.75),
    legend_labels = c("Absent", "Present"),
    cellheight = 18,
  )
  return(heatmap)
}

#' @keywords internal
getHeatmapPlotCorrelation <- function(plot_data) {
  # Convert list into a named vector for clusters
  row_cluster_assignment <- unlist(lapply(seq_along(plot_data$ordered_groups), function(i) {
    stats::setNames(rep(i, length(plot_data$ordered_groups[[i]])), plot_data$ordered_groups[[i]])
  }))

  # Ensure the matrix rows follow the order in row_groups
  ordered_row_names <- unlist(plot_data$ordered_groups)
  plot_data$ordered_matrix <- plot_data$ordered_matrix[ordered_row_names, , drop=FALSE]

  # Generate the heatmap with row clustering
  heatmap <- pheatmap::pheatmap(
    plot_data$ordered_matrix,
    cluster_rows = FALSE,   # Use computed row clustering
    cluster_cols = TRUE,      # Cluster columns
    gaps_row = cumsum(table(row_cluster_assignment)),  # Add row gaps
    show_colnames = FALSE,
    color = c("#e5f5f9", "#2ca25f"),
    treeheight_row = 50  # Show row dendrogram
  )

  return(heatmap)
}

#' @keywords internal
unique_names <- function(names) {
  # Truncate names to 60 characters
  short_names <- stringr::str_sub(names, 1, 60)

  # Identify duplicated names
  duplicated_names <- duplicated(short_names) | duplicated(short_names, fromLast = TRUE)

  # Apply suffix only to duplicated names
  if (any(duplicated_names)) {
    counts <- ave(short_names[duplicated_names], short_names[duplicated_names], FUN = seq_along)
    short_names[duplicated_names] <- paste(short_names[duplicated_names], counts, sep = "_")
  }

  return(short_names)
}
