
#' Generate a Prevalence Plot
#'
#' This function generates a prevalence plot using the CohortContrast GUI object.
#' It extracts necessary components from the ccObject and passes them to the
#' `getPrevalencePlot` function to generate the plot.
#'
#' @param ccObject An object returned by the CohortContrast GUI, typically created
#'        when the "Create Visual Snapshot" button is pressed. It should contain
#'        target_row_annotation, target_col_annotation, and target_matrix components.
#' @return A plot object generated by `getPrevalencePlot`.
#' @examples
#' \dontrun{
#' # Assuming `ccObject` (visual snapshot) is already created via CohortContrast GUI
#' ccObject <- readRDS("./visual_snapshots/CohortContrastDataVisualSnapshot.rds")
#' getPrevalencePlot(ccObject)
#' }
#' @export
getPrevalencePlot <- function(ccObject) {
  createPrevalencePlot(
    ccObject$filtered_target
  )
}


#' @keywords internal
createPrevalencePlot <- function(filtered_target, isCorrelationView = FALSE) {

  plot_data = getPrevalencePlotData(filtered_target, isCorrelationView = isCorrelationView)

  # Check if any concepts left
  if (is.null(plot_data)) {
    return(getErrorPlot())
  }

  # Heritage colors
  heritage_colors <- getHeritageColors()

  # Merge the colors into the main dataset
  plot_data <-
    merge(plot_data, heritage_colors, by = "HERITAGE", all.x = TRUE)

  if (isCorrelationView) {
    return(getPrevalencePlotCorrelation(plot_data))
  } else {
    return(getPrevalencePlotRegular(plot_data))
  }
}

#' @keywords internal
getPrevalencePlotData <- function(filtered_target, patientDataAllowed = TRUE, isCorrelationView = FALSE) {

  if (is.null(filtered_target) ||
      nrow(filtered_target$target_row_annotation) == 0) {
    return(NULL)
  }

  plotData <-
    as.data.frame(filtered_target$target_row_annotation) %>%
    tibble::rownames_to_column("CONCEPT_ID") %>%
    tibble::as_tibble() %>%
    dplyr::left_join(tibble::tibble(
      CONCEPT_ID = rownames(filtered_target$target_row_annotation),
      PRESENCE = if (is.null(nrow(filtered_target$target_matrix)) ||
                     nrow(filtered_target$target_matrix) == 1) {
        list(as.matrix(filtered_target$target_matrix)[, 1])
      } else {
        lapply(seq_len(nrow(filtered_target$target_matrix)), function(i)
          as.matrix(filtered_target$target_matrix)[i, ])
      }
    ),
    by = "CONCEPT_ID") %>%
    dplyr::mutate(PREVALENCE = purrr::map_dbl(.data$PRESENCE, mean)) %>%
    dplyr::mutate(AVERAGE_AGE = purrr::map_dbl(
      .data$PRESENCE,
      ~ mean(filtered_target$target_col_annotation[names(.x), "AGE"][as.logical(.x)],
             na.rm = TRUE)
    )) %>%
    dplyr::mutate(AVERAGE_AGE_OVERALL = mean(filtered_target$target_col_annotation$AGE, na.rm = TRUE)) %>%
    dplyr::mutate(AGE_DIFF = purrr::map(.data$PRESENCE, ~ {
      data <-
        filtered_target$target_col_annotation[names(.x), "AGE"][as.logical(.x)]
      if (length(data[!is.na(data)]) >= 2 &&
          length(unique(data[!is.na(data)])) > 1) {
        # Ensure there are at least two non-NA observations
        t.test(data)
      } else {
        list(
          estimate = mean(data, na.rm = TRUE),
          conf.int = c(mean(data, na.rm = TRUE), mean(data, na.rm = TRUE)),
          p.value = NA
        ) # Returning a list similar to t.test output structure
      }
    })) %>%
    dplyr::mutate(AGE_DIFF_ESTIMATE = purrr::map_dbl(.data$AGE_DIFF, ~ .x$estimate[1])) %>%
    dplyr::mutate(AGE_DIFF_LOW = purrr::map_dbl(.data$AGE_DIFF, ~ .x$conf.int[1])) %>%
    dplyr::mutate(AGE_DIFF_HIGH = purrr::map_dbl(.data$AGE_DIFF, ~ .x$conf.int[2])) %>%
    dplyr::mutate(AGE_DIFF_SIGNIFICANT = dplyr::if_else((.data$AGE_DIFF_HIGH > .data$AVERAGE_AGE_OVERALL) &
                                                          (.data$AGE_DIFF_LOW < .data$AVERAGE_AGE_OVERALL),
                                                        FALSE,
                                                        TRUE
    )) %>%
    dplyr::mutate(MALE_PROP = purrr::map_dbl(
      .data$PRESENCE,
      ~ mean(filtered_target$target_col_annotation[names(.x), "GENDER"][as.logical(.x)] == "Male", na.rm = TRUE)
    )) %>%
    dplyr::mutate(
      MALE_PROP_OVERALL = mean(
        filtered_target$target_col_annotation$GENDER == "Male",
        na.rm = TRUE
      )
    ) %>%
    dplyr::mutate(MALE_PROP_DIFF = purrr::map(.data$PRESENCE, ~ {
      data <-
        filtered_target$target_col_annotation[names(.x), "GENDER"][as.logical(.x)] == "Male"
      if (sum(data, na.rm = TRUE) >= 2 &&
          length(unique(data[!is.na(data)])) > 1) {
        # Ensure there are at least two non-NA observations
        t.test(data)
      } else {
        list(
          estimate = mean(data, na.rm = TRUE),
          conf.int = c(mean(data, na.rm = TRUE), mean(data, na.rm = TRUE)),
          p.value = NA
        )
      }
    })) %>%
    dplyr::mutate(MALE_PROP_DIFF_ESTIMATE = purrr::map_dbl(.data$MALE_PROP_DIFF, ~ .x$estimate)) %>%
    dplyr::mutate(MALE_PROP_DIFF_LOW = purrr::map_dbl(.data$MALE_PROP_DIFF, ~ .x$conf.int[1])) %>%
    dplyr::mutate(MALE_PROP_DIFF_HIGH = purrr::map_dbl(.data$MALE_PROP_DIFF, ~ .x$conf.int[2])) %>%
    dplyr::mutate(MALE_PROP_DIFF_SIGNIFICANT = dplyr::if_else((.data$MALE_PROP_DIFF_HIGH > .data$MALE_PROP_OVERALL) &
                                                                (.data$MALE_PROP_DIFF_LOW < .data$MALE_PROP_OVERALL),
                                                              FALSE,
                                                              TRUE
    )) %>%
    dplyr::mutate(
      PREVALENCE_LOG = dplyr::if_else(
        .data$PREVALENCE_DIFFERENCE_RATIO < 1,
        0,
        dplyr::if_else(
          .data$PREVALENCE_DIFFERENCE_RATIO > 100,
          2,
          log10(.data$PREVALENCE_DIFFERENCE_RATIO)
        )
      )
    )

  if (isCorrelationView) {
    # Extract ordered data
    ordered_matrix <- filtered_target$correlation_analysis$ordered_matrix
    gaps_row <- filtered_target$correlation_analysis$gaps_row

    # Reorder plotData based on ordered_matrix row order
    ordered_indices <- match(rownames(ordered_matrix), plotData$CONCEPT_NAME)
    plotData <- plotData[ordered_indices, ]

    # Add gaps as a grouping variable
    plotData$Group <- cut(seq_len(nrow(plotData)), breaks = c(0, gaps_row, nrow(plotData)), labels = FALSE)
  } else {
    plotData$Group = 1
  }

  if (!patientDataAllowed){
    plotData <- plotData %>% dplyr::select(.data$CONCEPT_ID, .data$CONCEPT_NAME, .data$HERITAGE, .data$PREVALENCE_DIFFERENCE_RATIO, .data$PREVALENCE, .data$PRESENCE, .data$ZTEST, .data$LOGITTEST, .data$AVERAGE_AGE,
                                           .data$AVERAGE_AGE_OVERALL, .data$AGE_DIFF, .data$AGE_DIFF_ESTIMATE, .data$AGE_DIFF_LOW, .data$AGE_DIFF_HIGH, .data$AGE_DIFF_SIGNIFICANT,
                                           .data$MALE_PROP, .data$MALE_PROP_OVERALL, .data$MALE_PROP_DIFF, .data$MALE_PROP_DIFF_ESTIMATE, .data$MALE_PROP_DIFF_LOW, .data$MALE_PROP_DIFF_HIGH,
                                           .data$MALE_PROP_DIFF_SIGNIFICANT, .data$PREVALENCE_LOG, .data$Group)
  }
  return(plotData)
}

#' @keywords internal
getPrevalencePlotRegular <- function(plot_data) {
  p1 <-
    ggplot2::ggplot(
      plot_data,
      ggplot2::aes(
        x = .data$PREVALENCE,
        y = stringr::str_sub(.data$CONCEPT_NAME, 1, 60),
        fill = 10 ** .data$PREVALENCE_LOG
      )
    ) +
    ggplot2::geom_bar(stat = "identity") +
    ggplot2::geom_text(
      ggplot2::aes(
        label = scales::label_comma(accuracy = 0.01)(10 ** .data$PREVALENCE_LOG),
        x = .data$PREVALENCE + 0.01  # Adjust position as needed
      ),
      hjust = 0, # Position text slightly to the right of the bar
      size = 3   # Adjust text size as desired
    ) +
    ggplot2::facet_grid(.data$HERITAGE ~ ., space = "free_y", scales = "free_y") +
    ggplot2::scale_fill_viridis_c(
      "\nRisk ratio (log10 scaled)\ncompared to background",
      limits = c(1, 100),
      trans = "log10",
      oob = scales::squish
    ) + # Ensure fill values are between 0 and 3
    ggplot2::scale_x_continuous(labels = scales::label_percent(),
                                sec.axis = ggplot2::dup_axis()) +
    ggplot2::ggtitle("Prevalence") +
    ggplot2::theme_bw() +
    ggplot2::theme(
      plot.title = ggplot2::element_text(hjust = 1),
      axis.title = ggplot2::element_blank(),
      legend.position = "top",
      legend.title = ggplot2::element_text(size = 10),
      strip.background = ggplot2::element_blank(),
      strip.text = ggplot2::element_blank(),
      panel.spacing = ggplot2::unit(0.5, "lines"),
      axis.text.y = ggplot2::element_text(size = 10) # Adjust the size as needed
    )

  p2 <-
    ggplot2::ggplot(plot_data,
                    ggplot2::aes(
                      y = stringr::str_sub(.data$CONCEPT_NAME, 1, 60),
                      color = .data$AGE_DIFF_SIGNIFICANT
                    )) +
    ggplot2::geom_point(ggplot2::aes(x = .data$AGE_DIFF_ESTIMATE)) +
    ggplot2::geom_errorbar(ggplot2::aes(
      xmin = .data$AGE_DIFF_LOW,
      xmax = .data$AGE_DIFF_HIGH
    ),
    linewidth = 1) +
    ggplot2::geom_vline(ggplot2::aes(xintercept = .data$AVERAGE_AGE_OVERALL),
                        color = "darkgreen") +
    ggplot2::scale_color_manual(values = c("grey60", "blue"),
                                breaks = c(FALSE, TRUE)) +
    ggplot2::scale_x_continuous(sec.axis = ggplot2::dup_axis()) +
    ggplot2::facet_grid(.data$HERITAGE ~ ., space = "free_y", scales = "free_y") +
    ggplot2::ggtitle("AGE in group") +
    ggplot2::theme_bw() +
    ggplot2::theme(
      plot.title = element_text(hjust = 1),
      axis.title = ggplot2::element_blank(),
      axis.text.y = ggplot2::element_blank(),
      axis.ticks.y = ggplot2::element_blank(),
      strip.background = ggplot2::element_blank(),
      strip.text = ggplot2::element_blank(),
      legend.position = "none",
      panel.spacing = ggplot2::unit(0.5, "lines")
    )

  # Heritage text dataset
  heritage_annot = plot_data %>%
    dplyr::mutate(CONCEPT_NAME = stringr::str_sub(.data$CONCEPT_NAME, 1, 60)) %>%
    dplyr::group_by(.data$HERITAGE) %>%
    dplyr::summarise(CONCEPT_NAME = max(.data$CONCEPT_NAME)) %>%
    dplyr::ungroup()

  # Create the plot with backgrounds
  p3 <-
    ggplot2::ggplot(
      plot_data,
      ggplot2::aes(
        y = stringr::str_sub(.data$CONCEPT_NAME, 1, 60),
        color = .data$MALE_PROP_DIFF_SIGNIFICANT
      )
    ) +
    ggplot2::geom_text(aes(label = .data$HERITAGE), x = 1, hjust = 1, size = 6, fontface = "bold", color = "navy", alpha = 0.5, data = heritage_annot) +
    ggplot2::geom_point(ggplot2::aes(x = .data$MALE_PROP_DIFF_ESTIMATE)) +
    ggplot2::geom_errorbar(
      ggplot2::aes(
        xmin = .data$MALE_PROP_DIFF_LOW,
        xmax = .data$MALE_PROP_DIFF_HIGH
      ),
      linewidth = 1
    ) +
    ggplot2::geom_vline(ggplot2::aes(xintercept = .data$MALE_PROP_OVERALL),
                        color = "darkgreen") +
    ggplot2::scale_color_manual(values = c("grey60", "blue"),
                                breaks = c(FALSE, TRUE)) +  # Colors for significant differences
    ggplot2::scale_x_continuous(labels = scales::label_percent(),
                                sec.axis = ggplot2::dup_axis(),
                                limits = c(0,1)) +
    ggplot2::facet_grid(.data$HERITAGE ~ ., space = "free_y", scales = "free_y") +
    ggplot2::ggtitle("Male percentage in group") +
    ggplot2::theme_bw() +
    ggplot2::guides(color = "none") +  # Hide the color guide
    ggplot2::theme(
      plot.title = ggplot2::element_text(hjust = 1),
      panel.spacing = ggplot2::unit(0.5, "lines"),
      strip.background = ggplot2::element_blank(),
      # Hide the strip background
      legend.position = "none",
      strip.text.x = ggplot2::element_blank(),
      # Remove facet labels
      # Place the fill guide (HERITAGE) at the bottom
      axis.title = ggplot2::element_blank(),
      axis.text.y = ggplot2::element_blank(),
      strip.text.y = ggplot2::element_blank(),
      axis.ticks.y = ggplot2::element_blank()
    )


  p <-
    p1 + p2 + p3 + patchwork::plot_layout(nrow = 1, heights = c(1, 1, 1))

  return(p)
}

#' @keywords internal
getPrevalencePlotCorrelation <- function(plot_data) {
  # Plot grouped heatmap with gaps_row handling
  p1 <- ggplot2::ggplot(
    plot_data,
    ggplot2::aes(
      x = .data$PREVALENCE,
      y = stringr::str_sub(.data$CONCEPT_NAME, 1, 60),
      fill = 10 ** .data$PREVALENCE_LOG
    )
  ) +
    ggplot2::geom_bar(stat = "identity") +
    ggplot2::geom_text(
      ggplot2::aes(
        label = scales::label_comma(accuracy = 0.01)(10 ** .data$PREVALENCE_LOG),
        x = .data$PREVALENCE + 0.01
      ),
      hjust = 0,
      size = 3
    ) +
    ggplot2::facet_grid(.data$Group ~ ., space = "free_y", scales = "free_y") +
    ggplot2::scale_fill_viridis_c(
      "\nRisk ratio (log10 scaled)\ncompared to background",
      limits = c(1, 100),
      trans = "log10",
      oob = scales::squish
    ) +
    ggplot2::scale_x_continuous(labels = scales::label_percent(),
                                sec.axis = ggplot2::dup_axis()) +
    ggplot2::ggtitle("Prevalence") +
    ggplot2::theme_bw() +
    ggplot2::theme(
      plot.title = ggplot2::element_text(hjust = 1),
      axis.title = ggplot2::element_blank(),
      legend.position = "top",
      legend.title = ggplot2::element_text(size = 10),
      strip.background = ggplot2::element_blank(),
      strip.text = ggplot2::element_blank(),
      panel.spacing = ggplot2::unit(0.5, "lines"),
      axis.text.y = ggplot2::element_text(size = 10)
    )

  p2 <- ggplot2::ggplot(
    plot_data,
    ggplot2::aes(
      y = .data$CONCEPT_NAME,
      x = .data$AGE_DIFF_ESTIMATE,
      color = .data$AGE_DIFF_SIGNIFICANT
    )
  ) +
    ggplot2::geom_point() +
    ggplot2::geom_errorbar(
      ggplot2::aes(
        xmin = .data$AGE_DIFF_LOW,
        xmax = .data$AGE_DIFF_HIGH
      ),
      linewidth = 1
    ) +
    ggplot2::geom_vline(
      ggplot2::aes(xintercept = .data$AVERAGE_AGE_OVERALL),
      color = "darkgreen"
    ) +
    ggplot2::facet_grid(Group ~ ., space = "free_y", scales = "free_y") +
    ggplot2::scale_color_manual(values = c("grey60", "blue")) +
    ggplot2::scale_x_continuous(sec.axis = ggplot2::dup_axis()) +
    ggplot2::theme_bw() +
    ggplot2::theme(
      plot.title = ggplot2::element_text(hjust = 1),
      axis.title = ggplot2::element_blank(),
      axis.text.y = ggplot2::element_blank(),
      axis.ticks.y = ggplot2::element_blank(),
      strip.background = ggplot2::element_blank(),
      strip.text = ggplot2::element_blank(),
      legend.position = "none",
      panel.spacing = ggplot2::unit(0.5, "lines")
    ) +
    ggplot2::ggtitle("Age in group")


  # Plot male proportion differences with gaps_row handling
  p3 <- ggplot2::ggplot(
    plot_data,
    ggplot2::aes(
      y = .data$CONCEPT_NAME,
      x = .data$MALE_PROP_DIFF_ESTIMATE,
      color = .data$MALE_PROP_DIFF_SIGNIFICANT
    )
  ) +
    ggplot2::geom_point() +
    ggplot2::geom_errorbar(
      ggplot2::aes(
        xmin = .data$MALE_PROP_DIFF_LOW,
        xmax = .data$MALE_PROP_DIFF_HIGH
      ),
      linewidth = 1
    ) +
    ggplot2::geom_vline(
      ggplot2::aes(xintercept = .data$MALE_PROP_OVERALL),
      color = "darkgreen"
    ) +
    ggplot2::facet_grid(Group ~ ., space = "free_y", scales = "free_y") +
    ggplot2::scale_color_manual(values = c("grey60", "blue")) +
    ggplot2::scale_x_continuous(labels = scales::label_percent(),
                                sec.axis = ggplot2::dup_axis(),
                                limits = c(0,1)) +
    ggplot2::theme_bw() +
    ggplot2::theme(
      plot.title = ggplot2::element_text(hjust = 1),
      axis.title = ggplot2::element_blank(),
      axis.text.y = ggplot2::element_blank(),
      axis.ticks.y = ggplot2::element_blank(),
      strip.background = ggplot2::element_blank(),
      strip.text = ggplot2::element_blank(),
      legend.position = "none",
      panel.spacing = ggplot2::unit(0.5, "lines")
    ) +
    ggplot2::ggtitle("Male percentage in group")

  # Combine plots
  p <-
    p1 + p2 + p3 + patchwork::plot_layout(nrow = 1, heights = c(1, 1, 1))

  return(p)
}
